spring:
  application:
    name: mail-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: rootroot

logging:
  level:
    root: INFO
    #DEBUG
server:
  port: 8081

kafka:
  host: localhost:9092
  topics:
    user-created:
      topic: user-service.send-mail.0
      consumerGroup: ${spring.application.name}-send-mail-consumer
      replicationFactor: 1
      retentionInMs: 604800000