spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: rootroot

logging:
  level:
    root: INFO
    #web: DEBUG
server:
  port: 8080
kafka:
  host: localhost:9092
  topics:
    registered-user:
      topicName: ${spring.application.name}.registered-user.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
    customized-mail:
      topicName: ${spring.application.name}.customized-mail.0
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000

